package steps

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/zoro11031/homelab-coreos-minipc/homelab-setup/internal/config"
	"github.com/zoro11031/homelab-coreos-minipc/homelab-setup/internal/system"
	"github.com/zoro11031/homelab-coreos-minipc/homelab-setup/internal/ui"
)

// Deployment handles service deployment
type Deployment struct {
	containers *system.ContainerManager
	fs         *system.FileSystem
	services   *system.ServiceManager
	config     *config.Config
	ui         *ui.UI
	markers    *config.Markers
}

// NewDeployment creates a new Deployment instance
func NewDeployment(containers *system.ContainerManager, fs *system.FileSystem, services *system.ServiceManager, cfg *config.Config, ui *ui.UI, markers *config.Markers) *Deployment {
	return &Deployment{
		containers: containers,
		fs:         fs,
		services:   services,
		config:     cfg,
		ui:         ui,
		markers:    markers,
	}
}

// FindComposeFiles searches for compose files in common locations
func (d *Deployment) FindComposeFiles() ([]string, error) {
	d.ui.Info("Searching for compose files...")

	// Common locations for compose files
	searchPaths := []string{
		filepath.Join(os.Getenv("HOME"), "setup", "compose-setup"),
		filepath.Join(os.Getenv("HOME"), "compose"),
		"/usr/share/compose-setup",
		"/usr/share/homelab-setup/compose",
	}

	var foundFiles []string

	for _, searchPath := range searchPaths {
		exists, err := d.fs.DirectoryExists(searchPath)
		if err != nil {
			continue
		}
		if !exists {
			continue
		}

		// Find .yml and .yaml files
		entries, err := os.ReadDir(searchPath)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if filepath.Ext(name) == ".yml" || filepath.Ext(name) == ".yaml" {
				fullPath := filepath.Join(searchPath, name)
				foundFiles = append(foundFiles, fullPath)
			}
		}
	}

	if len(foundFiles) > 0 {
		d.ui.Successf("Found %d compose file(s)", len(foundFiles))
		for _, file := range foundFiles {
			d.ui.Printf("  - %s", file)
		}
	} else {
		d.ui.Warning("No compose files found in standard locations")
	}

	return foundFiles, nil
}

// CopyComposeFiles copies compose files to the destination directory
func (d *Deployment) CopyComposeFiles(sourceFiles []string, destDir string) error {
	if len(sourceFiles) == 0 {
		d.ui.Info("No compose files to copy")
		return nil
	}

	d.ui.Infof("Copying compose files to %s...", destDir)

	// Ensure destination directory exists
	homelabUser := d.config.GetOrDefault("HOMELAB_USER", "")
	if err := d.fs.EnsureDirectory(destDir, homelabUser, 0755); err != nil {
		return fmt.Errorf("failed to create destination directory: %w", err)
	}

	for _, sourceFile := range sourceFiles {
		fileName := filepath.Base(sourceFile)
		destFile := filepath.Join(destDir, fileName)

		d.ui.Infof("Copying %s...", fileName)

		// TODO: Implement CopyFile method in FileSystem
		// For now, provide manual instructions
		d.ui.Info(fmt.Sprintf("  cp %s %s", sourceFile, destFile))
	}

	d.ui.Warning("Automatic file copying not yet implemented")
	d.ui.Info("Please manually copy compose files to the deployment directory")

	return nil
}

// GenerateEnvFile generates a .env file for compose services
func (d *Deployment) GenerateEnvFile(baseDir string) error {
	d.ui.Info("Generating environment file for compose services...")

	envFile := filepath.Join(baseDir, "compose", ".env")

	// Get configuration values
	puid := d.config.GetOrDefault("PUID", "1000")
	pgid := d.config.GetOrDefault("PGID", "1000")
	timezone := d.config.GetOrDefault("TIMEZONE", "America/Chicago")
	homelabUser := d.config.GetOrDefault("HOMELAB_USER", "homelab")

	// Build env file content
	envContent := fmt.Sprintf(`# Homelab Environment Configuration
# Generated by homelab-setup

# User/Group IDs for containers
PUID=%s
PGID=%s

# Timezone
TZ=%s

# Homelab User
HOMELAB_USER=%s

# Base Directory
HOMELAB_BASE_DIR=%s

# Data Directories
CONFIG_DIR=%s
DATA_DIR=%s
`, puid, pgid, timezone, homelabUser, baseDir,
		filepath.Join(baseDir, "config"),
		filepath.Join(baseDir, "data"))

	// Add NFS configuration if available
	nfsServer := d.config.GetOrDefault("NFS_SERVER", "")
	if nfsServer != "" {
		nfsMountPoint := d.config.GetOrDefault("NFS_MOUNT_POINT", "")
		envContent += fmt.Sprintf(`
# NFS Configuration
NFS_SERVER=%s
NFS_MOUNT_POINT=%s
`, nfsServer, nfsMountPoint)
	}

	d.ui.Print("")
	d.ui.Info("Environment file content:")
	d.ui.Print(envContent)
	d.ui.Print("")

	// TODO: Implement WriteFile in FileSystem
	d.ui.Warning("Automatic .env file creation not yet implemented")
	d.ui.Infof("Please create %s with the content shown above", envFile)

	return nil
}

// ListServices lists available services to deploy
func (d *Deployment) ListServices() ([]string, error) {
	// For now, return empty list
	// In a real implementation, this would scan for available services
	services := []string{}

	d.ui.Info("Service deployment is manual at this stage")
	d.ui.Info("You will need to:")
	d.ui.Info("  1. Place your docker-compose.yml files in the compose directory")
	d.ui.Info("  2. Configure service-specific environment variables")
	d.ui.Info("  3. Start services using docker-compose or podman-compose")

	return services, nil
}

// DisplayInstructions displays manual deployment instructions
func (d *Deployment) DisplayInstructions() {
	baseDir := d.config.GetOrDefault("HOMELAB_BASE_DIR", "/mnt/homelab")
	runtime := d.config.GetOrDefault("CONTAINER_RUNTIME", "podman")

	d.ui.Print("")
	d.ui.Info("Manual Deployment Instructions:")
	d.ui.Separator()
	d.ui.Print("")

	d.ui.Info("1. Navigate to the compose directory:")
	d.ui.Printf("   cd %s", filepath.Join(baseDir, "compose"))
	d.ui.Print("")

	d.ui.Info("2. Review and customize your docker-compose.yml files")
	d.ui.Print("")

	d.ui.Info("3. Start services:")
	if runtime == "podman" {
		d.ui.Print("   podman-compose up -d")
		d.ui.Print("   # or")
		d.ui.Print("   podman compose up -d")
	} else {
		d.ui.Print("   docker-compose up -d")
		d.ui.Print("   # or")
		d.ui.Print("   docker compose up -d")
	}
	d.ui.Print("")

	d.ui.Info("4. Check service status:")
	if runtime == "podman" {
		d.ui.Print("   podman-compose ps")
		d.ui.Print("   podman ps")
	} else {
		d.ui.Print("   docker-compose ps")
		d.ui.Print("   docker ps")
	}
	d.ui.Print("")

	d.ui.Info("5. View logs:")
	if runtime == "podman" {
		d.ui.Print("   podman-compose logs -f <service-name>")
	} else {
		d.ui.Print("   docker-compose logs -f <service-name>")
	}
	d.ui.Print("")

	d.ui.Info("For systemd service management:")
	d.ui.Info("  - Create systemd service units in ~/.config/systemd/user/")
	d.ui.Info("  - Enable services: systemctl --user enable <service>")
	d.ui.Info("  - Start services: systemctl --user start <service>")
	d.ui.Info("  - Enable linger: loginctl enable-linger $USER")
	d.ui.Print("")
}

// Run executes the deployment step
func (d *Deployment) Run() error {
	// Check if already completed
	exists, err := d.markers.Exists("services-deployed")
	if err != nil {
		return fmt.Errorf("failed to check marker: %w", err)
	}
	if exists {
		d.ui.Info("Services already deployed (marker found)")
		d.ui.Info("To re-run, remove marker: ~/.local/homelab-setup/services-deployed")
		return nil
	}

	d.ui.Header("Service Deployment")
	d.ui.Info("Preparing for service deployment...")
	d.ui.Print("")

	// Get base directory
	baseDir := d.config.GetOrDefault("HOMELAB_BASE_DIR", "")
	if baseDir == "" {
		return fmt.Errorf("base directory not configured (run directory setup first)")
	}

	// Find compose files
	d.ui.Step("Locating Compose Files")
	composeFiles, err := d.FindComposeFiles()
	if err != nil {
		d.ui.Warning(fmt.Sprintf("Error finding compose files: %v", err))
	}

	// Copy compose files (if found)
	if len(composeFiles) > 0 {
		d.ui.Step("Copying Compose Files")
		destDir := filepath.Join(baseDir, "compose")
		if err := d.CopyComposeFiles(composeFiles, destDir); err != nil {
			d.ui.Warning(fmt.Sprintf("Failed to copy compose files: %v", err))
		}
	}

	// Generate environment file
	d.ui.Step("Generating Environment Configuration")
	if err := d.GenerateEnvFile(baseDir); err != nil {
		d.ui.Warning(fmt.Sprintf("Failed to generate .env file: %v", err))
	}

	// List services (informational)
	d.ui.Step("Available Services")
	if _, err := d.ListServices(); err != nil {
		d.ui.Warning(fmt.Sprintf("Failed to list services: %v", err))
	}

	// Display deployment instructions
	d.ui.Step("Deployment Instructions")
	d.DisplayInstructions()

	d.ui.Print("")
	d.ui.Separator()
	d.ui.Success("✓ Deployment preparation completed")
	d.ui.Info("Follow the instructions above to deploy your services")

	// Create completion marker
	if err := d.markers.Create("services-deployed"); err != nil {
		return fmt.Errorf("failed to create completion marker: %w", err)
	}

	return nil
}
