---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: homelab-coreos-minipc
description: Frontend application node for NAB9 mini PC

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore
image-version: stable

modules:
  - from-file: packages.yml
  # Copy system configuration files (includes /etc/profile.d/intel-vaapi.sh)
  - type: files
    files:
      - source: system
        destination: /
  # Copy dotfiles directory to core user's home
  - type: files
    files:
      - source: dotfiles
        destination: /var/home/core/.dotfiles
        user: core
        group: core
  - from-file: systemd.yml

  - type: signing
