---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: homelab-coreos-minipc
description: Frontend application node for NAB9 mini PC

base-image: ghcr.io/ublue-os/ucore
image-version: latest

modules:
  - type: dnf
    install:
      packages:
        - wireguard-tools
        - nfs-utils
        - intel-media-driver
        - libva-utils

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - wg-quick@wg0.service
        - mnt-nas-media.mount
        - mnt-nas-nextcloud.mount
        - mnt-nas-immich.mount

  - type: signing
