version: '3.9'

# Cloud Services - Nextcloud and Immich
# These services store data on NFS mounts and are accessed via VPS reverse proxy

services:
  # Nextcloud - Personal cloud and groupware
  nextcloud:
    image: docker.io/library/nextcloud:apache
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      # Database configuration
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=${NEXTCLOUD_DB_DATABASE:-nextcloud}
      - POSTGRES_USER=${NEXTCLOUD_DB_USERNAME:-nc_user}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}

      # Redis configuration
      - REDIS_HOST=nextcloud-redis

      # Trusted domains and URL overrides
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-cloud.example.com}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_OVERWRITE_HOST:-cloud.example.com}
      - OVERWRITECLIURL=https://${NEXTCLOUD_OVERWRITE_HOST:-cloud.example.com}

      # PHP configuration
      - PHP_MEMORY_LIMIT=${NEXTCLOUD_PHP_MEMORY_LIMIT:-1024M}
      - PHP_UPLOAD_LIMIT=${NEXTCLOUD_PHP_UPLOAD_LIMIT:-1024M}

      # User and timezone
      - TZ=${TZ:-America/New_York}
    volumes:
      - /mnt/nas-nextcloud/nextcloud/html:/var/www/html:z
      - /mnt/nas-nextcloud/data:/var/www/html/data:z
      - /mnt/nas-nextcloud/nextcloud/custom_apps:/var/www/html/custom_apps:z
      - /mnt/nas-nextcloud/nextcloud/config:/var/www/html/config:z
      - /mnt/nas-nextcloud/nextcloud/themes:/var/www/html/themes:z
    ports:
      - "8080:80"
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Nextcloud background jobs (cron)
  nextcloud-cron:
    image: docker.io/library/nextcloud:apache
    container_name: nextcloud-cron
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    entrypoint: /cron.sh
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - /mnt/nas-nextcloud/nextcloud/html:/var/www/html:z
      - /mnt/nas-nextcloud/data:/var/www/html/data:z
      - /mnt/nas-nextcloud/nextcloud/custom_apps:/var/www/html/custom_apps:z
      - /mnt/nas-nextcloud/nextcloud/config:/var/www/html/config:z
      - /mnt/nas-nextcloud/nextcloud/themes:/var/www/html/themes:z
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # PostgreSQL database for Nextcloud
  nextcloud-db:
    image: docker.io/library/postgres:16-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_DATABASE:-nextcloud}
      - POSTGRES_USER=${NEXTCLOUD_DB_USERNAME:-nc_user}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${APPDATA_PATH}/nextcloud/db:/var/lib/postgresql/data:Z
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Redis cache for Nextcloud
  nextcloud-redis:
    image: docker.io/library/redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Collabora Online - Office document editing (optional)
  collabora:
    image: docker.io/collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
      - username=${COLLABORA_USERNAME:-admin}
      - password=${COLLABORA_PASSWORD}
      - domain=${COLLABORA_DOMAIN:-cloud\\.example\\.com}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    ports:
      - "9980:9980"
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Immich - Self-hosted photo and video backup
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    command: ['start.sh', 'immich']
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${IMMICH_DB_USERNAME:-postgres}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE:-immich}
      - REDIS_HOSTNAME=immich-redis
      - UPLOAD_LOCATION=/mnt/nas-immich
    volumes:
      - /mnt/nas-immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:3001"
    depends_on:
      - immich-redis
      - immich-postgres
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-microservices
    restart: unless-stopped
    command: ['start.sh', 'microservices']
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${IMMICH_DB_USERNAME:-postgres}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_DATABASE:-immich}
      - REDIS_HOSTNAME=immich-redis
      - UPLOAD_LOCATION=/mnt/nas-immich
    volumes:
      - /mnt/nas-immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich-redis
      - immich-postgres
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-machine-learning
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${APPDATA_PATH}/immich/model-cache:/cache
    networks:
      - cloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-redis:
    image: redis:7.2-alpine
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - cloud

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}
      - POSTGRES_USER=${IMMICH_DB_USERNAME:-postgres}
      - POSTGRES_DB=${IMMICH_DB_DATABASE:-immich}
    volumes:
      - ${APPDATA_PATH}/immich/postgres:/var/lib/postgresql/data
    networks:
      - cloud

networks:
  cloud:
    name: cloud
    driver: bridge
