version: '3.9'

# Web Services - Overseerr and Wizarr
# These services are accessed via VPS reverse proxy (WireGuard tunnel)

services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    ports:
      - "5055:5055"
    volumes:
      - ${APPDATA_PATH}/overseerr:/config
    networks:
      - web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    ports:
      - "5690:5690"
    volumes:
      - ${APPDATA_PATH}/wizarr:/data/database
    networks:
      - web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Optional: Organizr for unified dashboard
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    ports:
      - "9983:80"
    volumes:
      - ${APPDATA_PATH}/organizr:/config
    networks:
      - web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Optional: Homepage dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "3000:3000"
    volumes:
      - ${APPDATA_PATH}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  web:
    name: web
    driver: bridge
